swagger: '2.0'
info:
  description: Move your app forward with the Snabb API
  version: 1.0.0
  title: Snabb API
  contact:
    name: Snabb Dev Systems
    url: developers.snabb.io
    email: dev.systems@snabb.io
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  OauthApplicationSecurity:
    type: oauth2
    flow: application
    tokenUrl: 'https://api.snabb.io/api/v1/o/token'
    scopes:
      admin: Admin scope
      user: User scope
      api: API scope
  OauthPasswordSecurity:
    type: oauth2
    flow: password
    tokenUrl: 'https://api.snabb.io/api/v1/o/token'
    scopes:
      admin: Admin scope
      user: User scope

security:
  - OauthApplicationSecurity:
    - api
  - OauthPasswordSecurity:
    - user

paths:
  $ref: ./api/paths/index.yaml
definitions:
  $ref: ./api/definitions/index.yaml
