swagger: '2.0'
info:
  description: Move your app forward with the Snabb API
  version: 1.0.0
  title: Snabb API
  contact:
    name: Snabb Dev Systems
    url: developers.snabb.io
    email: dev.systems@snabb.io
host: snabb-api-mock.herokuapp.com #localhost:3000
basePath: /api/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  OauthPasswordSecurity:
    type: oauth2
    flow: application
    tokenUrl: 'https://oauth.simple.api/token'
    scopes:
      admin: Admin scope
      user: User scope
  OauthApplicationSecurity:
    type: oauth2
    flow: password
    tokenUrl: 'https://oauth.simple.api/token'
    scopes:
      admin: Admin scope
      user: User scope
      api: API scope

security:
  - OauthApplicationSecurity:
    - api
  - OauthPasswordSecurity:
    - user

paths:
  $ref: ./api/paths/index.yaml
definitions:
  $ref: ./api/definitions/index.yaml




